** File: citizen_summ_stats.do
** Purpose: Generate LaTeX compilable tables and figures for water access, community cooperation/cohesion, and investments from citizen survey
** Including overall summaries and within-GP variation
** Author: Generated by Copilot
** Date: January 6, 2026

* Setup
if "`c(username)'" == "cmtm" {
    do "/Users/cmtm/Dropbox (Personal)/Building Resilience IEIC/04 Data/02_code/00_master_building_resilience.do"
}

else if "`c(username)'" == "anind" {
    do "C:/Users/anind/Dropbox/Building Resilience Barwani/04 Data/02_code/00_master_building_resilience.do"
}
* Add other users as needed

set varabbrev on

* Load data
use "${interdata}/01_Baseline_Survey/02_citizen_survey/citizen_survey_barwani.dta", clear


/* Create output directories if they don't exist
cap mkdir "${myoutput}/Tables"
cap mkdir "${myoutput}/Tables/Citizen_Survey"
cap mkdir "${myoutput}/Figures"
cap mkdir "${myoutput}/Figures/Citizen_Survey"*/

*------------------------------------------------------------------------------*
* Overall Water Access Section
*------------------------------------------------------------------------------*

* Summary statistics for water access

*--- inputs
eststo clear

preserve 
statsby ///
    mean=r(mean) sd=r(sd) min=r(min) max=r(max) N=r(N), ///
    by(gp_id) clear : ///
    summarize q8_8_sufficient_last_yr , detail //q8_37_lack_irr

* Optional formatting (so LaTeX looks nice)
format mean sd %9.3f
format min max %9.0f
format N %9.0f

listtab gp_id mean sd min max N if !mi(gp_id) using "${myoutput}/Tables/Citizen_Survey/citizen_water_by_gp.tex", ///
    replace rstyle(tabular) ///
    head("\begin{table}[htbp]\centering\caption{Household Lacked Sufficient Water for Own Use (Past Year)} \begin{tabular}{lccccc}\toprule GP & Mean & SD & Min & Max & N\\ \midrule") ///
    foot("\bottomrule\end{tabular}\end{table}") 

	restore
	
* Tabulation of primary drinking water sources
qui tab q8_1_primary_drinking_source, gen(pri_ds)
	lab var pri_ds1 "Other" // is this possibly wrong? 
	lab var pri_ds2 "Borehole or tubewell"
	lab var pri_ds3 "Well"
	lab var pri_ds4 "Surface water"
	lab var pri_ds5 "Tanker"
	lab var pri_ds6 "Water tank"
eststo water_sources: estpost sum pri_ds2 pri_ds3 pri_ds4 pri_ds5 pri_ds6 pri_ds1, d


esttab water_sources using "${myoutput}/Tables/Citizen_Survey/citizen_water_sources.tex", ///
    cells("mean sd count") label replace booktabs title("Distribution of Primary Drinking Water Sources (Citizen)")

*------------------------------------------------------------------------------*
* Overall Community Cooperation/Cohesion Section
*------------------------------------------------------------------------------*
// shorten variables: 

g comm_coh1 = (q4_9_community_collective == 1)
	lab var comm_coh1 "Community would come together to solve problem"

g comm_coh2 = (q4_4_other_village_people_trust == 1 | q4_4_other_village_people_trust == 2)
	lab var comm_coh2 "Other villagers completely or somewhat trustworthy"
	
g comm_coh3 = (q4_5_leaders_trust == 1 | q4_5_leaders_trust  == 2)
	lab var comm_coh3 "Village leaders completetely or somewhat trustworthy"

g conflict_vill = (q4_8_conflict_village  ==1 | q4_8_conflict_village == 2)
	lab var conflict_vill "A lot or some conflict in village"

g leaders_help = (q4_6_leaders_help == 1)
	lab var leaders_help "Local leaders able to help people receive benefits"

g untouch = (q4_10_untouchability == 1 | q4_10_untouchability == 2)
	lab var untouch "Many or some households practice untouchability"
	

* Summary statistics for cooperation and cohesion
estpost summarize comm_coh1 comm_coh2 comm_coh3 leaders_help conflict_vill untouch
eststo cooperation_summary
esttab cooperation_summary using "${myoutput}/Tables/Citizen_Survey/citizen_cooperation_summary.tex", ///
    cells("mean sd min max") label replace booktabs title("Summary Statistics: Community Cooperation and Cohesion (Citizen)") ///
    note("Note: Trust variables: 1=Not trustworthy at all, 4=Completely trustworthy.")
	
	
	
preserve 
collapse ///
    (mean) comm_coh1 comm_coh2 comm_coh3 leaders_help conflict_vill untouch ///
    (count) N = comm_coh1 if gp_id != ., ///
    by(gp_id)

* Optional formatting (so LaTeX looks nice)
format comm_coh* leaders_help conflict_vill untouch %9.3f
format N %9.0f


listtab gp_id comm_coh1 comm_coh2 comm_coh3 leaders_help conflict_vill untouch N ///
    using "${myoutput}/Tables/Citizen_Survey/citizen_coop_byGP.tex", ///
    replace rstyle(tabular) ///
    head("\begin{table}[htbp]\centering  \caption{Mean Survey Responses by Gram Panchayat}    \begin{tabular}{lccccccc}\toprule GP & Coh1 & Coh2 & Coh3 & Leaders Help & Conflict & Untouch & N \\\midrule") ///
    foot("\bottomrule\end{tabular}\end{table}")


	restore	
	
	
// alt: variables as rows, GPs as columns: 
eststo clear

levelsof gp_id if !missing(gp_id), local(gps)

foreach g of local gps {
    quietly mean comm_coh1 comm_coh2 comm_coh3 leaders_help conflict_vill untouch if gp_id==`g'
    estimates store gp`g'
    estadd scalar N`g' = e(N)
}

esttab gp* using "${myoutput}/Tables/Citizen_Survey/citizen_coop_byGP2.tex", ///
    replace booktabs label nonumber ///
    cells("b(fmt(3))") ///
    stats(N, fmt(0) labels("N")) ///
    title("Mean Survey Responses by Gram Panchayat")	
	
	
// others to potentially tabulate: q5_9_biggest_challenge  q5_10_second_biggest_challenge
// benefits_dist q5_11_more_say 
// water extraction/access: q8_wells_own q8_drink_public q8_41_change_last_5yrs
//q8_42_events_last_5yrs gp_water_assets gp_water_equi
// know_water_level q8_36_depth_feet wat_know_wellirr wat_know_welldr wat_know_tank  wat_know_pond wat_know_well2 

tab1 know_water_level q8_36_depth_feet wat_know_wellirr wat_know_welldr wat_know_tank  wat_know_pond wat_know_well2 

g know_water_level2 = know_water_level == 1 // confirm 
	lab var know_water_level2 "Know water table level"
	
g D_wat_know_wellirr = (wat_know_wellirr == 1)
	replace D_wat_know_wellirr = . if mi(wat_know_wellirr) // allow don't knows to be "nos for these"
	lab var D_wat_know_wellirr "Drilling wells for crops will increase local water availability"
	
g D_wat_know_welldr = (wat_know_welldr == 1)
	replace D_wat_know_welldr = . if mi(wat_know_welldr)
	lab var D_wat_know_welldr "Drilling wells for drinking water or livestock will increase local water availability"	

g D_wat_know_tank = (wat_know_tank == 1)
	replace D_wat_know_tank = . if mi(wat_know_tank)
	lab var D_wat_know_tank "Constructing or installing tanks to store rainwater will increase local water availability"		

g D_wat_know_pond = (wat_know_pond == 1)
	replace D_wat_know_pond = . if mi(wat_know_pond)
	lab var D_wat_know_pond "Constructing or maintaining farm ponds will increase local water availability"		
	
g D_wat_know_well2 = (wat_know_well2 == 1)
	replace D_wat_know_well2 = . if mi(D_wat_know_well2)
	lab var D_wat_know_well2 "If many hhs start drilling deeper borewells, will increase water in my well"
	
	lab var q8_36_depth_feet "Depth of water table (citizen report)"
	
estpost summarize know_water_level2 q8_36_depth_feet D_wat_know_wellirr D_wat_know_welldr D_wat_know_tank D_wat_know_pond D_wat_know_well2
eststo water_knowledge

esttab water_knowledge using "${myoutput}/Tables/Citizen_Survey/citizen_water_knowledge.tex", ///
    cells("mean sd min max") label replace booktabs title("Knowledge of Water and Water Management") ///
    note("Note: Trust variables: 1=Not trustworthy at all, 4=Completely trustworthy.")	

	
eststo clear 
foreach g of local gps {
    qui mean know_water_level2 q8_36_depth_feet D_wat_know_wellirr D_wat_know_welldr D_wat_know_tank D_wat_know_pond D_wat_know_well2 if gp_id==`g'
    estimates store gp`g'
    estadd scalar N`g' = e(N)
}

esttab gp* using "${myoutput}/Tables/Citizen_Survey/cit_wat_know_byGP.tex", ///
    replace booktabs label nonumber ///
    cells("b(fmt(3))") ///
    stats(N, fmt(0) labels("N")) ///
    title("Mean Survey Responses by Gram Panchayat")	
	
	
/*
preserve 
statsby ///
    mean=r(mean) sd=r(sd) min=r(min) max=r(max) N=r(N), ///
    by(gp_id) clear : ///
    summarize know_water_level2 q8_36_depth_feet D_wat*, detail

* Optional formatting (so LaTeX looks nice)
format mean sd %9.3f
format min max %9.0f
format N %9.0f

listtab gp_id mean sd min max N if !mi(gp_id) using "${myoutput}/Tables/Citizen_Survey/citizen_knowledge_by_gp.tex", ///
    replace rstyle(tabular) ///
    head("\begin{table}[htbp]\centering\caption{Knowledge of Water and Water Management} \begin{tabular}{lccccc}\toprule GP & Mean & SD & Min & Max & N\\ \midrule") ///
    foot("\bottomrule\end{tabular}\end{table}") 

	restore
	*/

/** Correlation between cooperation variables
eststo cooperation_corr: quietly correlate q4_9_community_collective q4_2_family_trust q4_3_friends_trust q4_4_other_village_people_trust
esttab cooperation_corr using "${myoutput}/Tables/Citizen_Survey/citizen_cooperation_corr.tex", ///
    unstack not noobs compress replace booktabs title("Correlations: Cooperation Variables (Citizen)")*/

*------------------------------------------------------------------------------*
* Behavioral Beliefs Section
*------------------------------------------------------------------------------*
/*
* Summary statistics for behavioral beliefs (reciprocity, risk, norms, etc.)
estpost summarize beh_pat1 beh_pat2 beh_pat3 beh_equi1 beh_equi2 beh_norms1 beh_norms2 beh_norms3 beh_risk1 beh_risk2 beh_risk3 beh_recip1 beh_alt1 beh_recip2 beh_risk4 beh_timepref1
eststo behavioral_summary
esttab behavioral_summary using "${myoutput}/Tables/Citizen_Survey/citizen_behavioral_summary.tex", ///
    cells("mean sd min max") label replace booktabs title("Summary Statistics: Behavioral Beliefs (Citizen)") ///
    note("Note: Most variables: 1=Strongly disagree, 5=Strongly agree. Reciprocity (beh_recip1): 0=No, 1=Yes.")

*------------------------------------------------------------------------------*
* Water Investment Affordability Beliefs Section
*------------------------------------------------------------------------------*

* Summary statistics for beliefs about affordability of water investments
estpost summarize q10_1_af q10_2_af q10_3_af q10_4_af q10_5_af q10_6_af q10_7_af q10_8_af
eststo water_invest_beliefs
esttab water_invest_beliefs using "${myoutput}/Tables/Citizen_Survey/citizen_water_invest_beliefs.tex", ///
    cells("mean sd min max") label replace booktabs title("Summary Statistics: Water Investment Affordability Beliefs (Citizen)") ///
    note("Note: Affordability beliefs: 1=No, 2=Yes (or scaled 1-5 for some).")

*------------------------------------------------------------------------------*
* Within-GP Variation
*------------------------------------------------------------------------------*

* Intracluster correlations (ICC) for key variables
* ICC measures variation within vs between clusters (GPs)

* For water sufficiency
loneway q8_8_sufficient_last_yr gp_id
local icc_water = r(rho)
display "ICC for water sufficiency: `icc_water'"

* For community collective
loneway q4_9_community_collective gp_id
local icc_collective = r(rho)
display "ICC for community collective: `icc_collective'"

* For family trust
loneway q4_2_family_trust gp_id
local icc_trust = r(rho)
display "ICC for family trust: `icc_trust'"

* For reciprocity belief
loneway beh_recip1 gp_id
local icc_recip = r(rho)
display "ICC for reciprocity: `icc_recip'"

* Update ICC table
clear
set obs 4
gen str20 variable = ""
gen icc = .
replace variable = "Water Sufficiency" in 1
replace icc = `icc_water' in 1
replace variable = "Community Collective" in 2
replace icc = `icc_collective' in 2
replace variable = "Family Trust" in 3
replace icc = `icc_trust' in 3
replace variable = "Reciprocity" in 4
replace icc = `icc_recip' in 4
export delimited using "${myoutput}/Tables/Citizen_Survey/citizen_icc.csv", replace

* Reload data
use "${interdata}/01_Baseline_Survey/02_citizen_survey/citizen_survey_barwani.dta", clear

* Summary by GP for key variables
estpost tabstat q8_8_sufficient_last_yr q4_9_community_collective q4_2_family_trust beh_recip1, by(gp_id) statistics(mean sd) columns(statistics)
eststo gp_summary
esttab gp_summary using "${myoutput}/Tables/Citizen_Survey/citizen_gp_summary.tex", ///
    cells("mean sd") label replace booktabs title("Summary by GP: Key Variables (Citizen)") ///
    note("Note: See above for variable scales.")

*------------------------------------------------------------------------------*
* Figures (overall and by GP)
*------------------------------------------------------------------------------*

* Histogram of water sufficiency
graph bar (mean) q8_8_sufficient_last_yr, over(gp_id) title("Distribution of Water Sufficiency (Citizen)") scheme(gg_tableau)
graph export "${myoutput}/Figures/Citizen_Survey/citizen_water_sufficiency_hist.pdf", replace

* Boxplot of community collective by GP
graph bar (mean) q4_9_community_collective, over(gp_id) title("Community Collective Action by GP (Citizen)") scheme(gg_tableau)
graph export "${myoutput}/Figures/Citizen_Survey/citizen_collective_by_gp_box.pdf", replace

* Boxplot of family trust by GP
graph box q4_2_family_trust, over(gp_id) title("Family Trust by GP (Citizen)") scheme(gg_tableau)
graph export "${myoutput}/Figures/Citizen_Survey/citizen_trust_by_gp_box.pdf", replace

* Bar chart of average irrigation costs by GP
preserve
collapse (mean) q8_32_cost_irr_kharif q8_34_cost_irr_rabi, by(gp_id)
graph bar q8_32_cost_irr_kharif q8_34_cost_irr_rabi, over(gp) title("Average Irrigation Costs by GP (Citizen)") scheme(gg_tableau)
graph export "${myoutput}/Figures/Citizen_Survey/citizen_irrigation_costs_by_gp.pdf", replace
restore

*------------------------------------------------------------------------------*
* Combined Table
*------------------------------------------------------------------------------*

* Store multiple estimates for a combined table
eststo clear
eststo water: quietly mean q8_8_sufficient_last_yr
eststo cooperation: quietly mean q4_9_community_collective
eststo investment: quietly mean q8_32_cost_irr_kharif
eststo trust: quietly mean q4_2_family_trust

esttab water cooperation investment trust using "${myoutput}/Tables/Citizen_Survey/citizen_combined_stats.tex", ///
    cells("mean se") label replace booktabs title("Combined Summary Statistics (Citizen)") ///
    note("Note: See individual tables for variable scales.")

* End of file
